### ISSUE TITLE
The weight for 4 extra_conv to get hierarchical feature in IPE

### ISSUE THREAD

**Issue by Zhengyang1995** [chenqi1126/SIPE#10]
Hey, according to your paper and code, there are 4 extra_conv to get hierarchical feature in IPE, I guess their main effort is to reduce dimensionality.  
My question is how do you update their weights when only IPE works, (as mentioned in table 4, miou reaches 53.2% ).
I could understand that in the total framework, the weight could be updated by the Lgsc loss, but in only IPE, there is only Lcls, how could you update their weights then?

**Comment by chenqi1126** [comment]
Hi @Zhengyang1995 ,

Thanks for your attention. IS-CAM with only IPE (53.2%) uses the semantic feature instead of the hierarchical feature for lacking Lgsc loss.

**Comment by Zhengyang1995** [comment]
Okay, I get it, thank you~

**Comment by Zhengyang1995** [comment]
Do you publish the weight for only IPE or the codes? How could I only run this part in your available codes? Thanks~

**Comment by chenqi1126** [comment]
You can train a vanilla Resnet50 with only cross-entropy loss, and then replace the hierarchical feature (hie_fea) with semantic feature (x4) in the following two lines: https://github.com/chenqi1126/SIPE/blob/e0c6a3bc578a6bade2cf85fe34a1793dce71170d/network/resnet50_SIPE.py#L149-L150

**Comment by Zhengyang1995** [comment]
Okay, thanks~
