### ISSUE TITLE
About the pertained backbone for DeepLab V2

### ISSUE THREAD

**Issue by tomtomsa** [chenqi1126/SIPE#11]
Hi,
 Thanks for your interesting work. I notice that you have trained a DeepLabV2 semantic segmentation network. Regarding the pre training of ResNet101, is it on COCO or ImageNet? I notice that you give two repo ([deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch) and [seamv1](https://github.com/YudeWang/semantic-segmentation-codebase/tree/main/experiment/seamv1-pseudovoc).) as guidance, but [deeplab-pytorch](https://github.com/kazuto1011/deeplab-pytorch) uses COCO pretrained weights, and [seamv1](https://github.com/YudeWang/semantic-segmentation-codebase/tree/main/experiment/seamv1-pseudovoc) uses ImageNet pretrained weights.  Since you didnot explain it in the paper or this repo, I open this issue for the answer.  Looking forward to your reply.

Sincerely,
Tomsa.

**Comment by chenqi1126** [comment]
@tomtomsa,

Thanks for your attention!

Yes - for a fair comparison on VOC dataset, we follow the previous works that use COCO pretrained weights to initialize ResNet101 and ImageNet pretrained weights to initialize WideResNet38.
Noted that for training COCO dataset, we use ImageNet pretrained weights to initialize both two backbones.

**Comment by tomtomsa** [comment]
@chenqi1126 I see, thank you for your reply.
