### ISSUE TITLE
Why do you use the path:train_ but not trainaug_ during make_cam.py?

### ISSUE THREAD

**Issue by yangxinhaosmu** [chenqi1126/SIPE#2]
Thanks for your work! When I follow the setting of make_cam.py, I get an exception during train_irn.py which shows that FileNotFoundError: No such file 'XXXX/SIPE-main/exp/ir_label/2010_000317.png'. Then I found that there is no 2010_000317.png in train_voc. How can I solve it?

**Comment by chenqi1126** [comment]
Hi @yangxinhaosmu, thanks for your attention. You need to change the infer dataset from 'train_voc.txt' to 'trainaug_voc.txt' to make all 10582 cams for training irn.
