### ISSUE TITLE
After I run make_seg_labels.py, the pseudo labels are all black.

### ISSUE THREAD

**Issue by yangxinhaosmu** [chenqi1126/SIPE#3]
But I run eval_sem_seg.py, the miou is not 0 but 69. How can I solve it? Thanks.

**Comment by chenqi1126** [comment]
The pseudo labels are assigned with their class indexes ranging from 0 to 20 (for VOC dataset) so they look all black. You can convert them to color maps with some palette tools as follows.
https://github.com/chenqi1126/SIPE/blob/66513a2a33d563434dd7ba7b80e8071b58c94cb4/make_seg_labels.py#L59-L61
