### ISSUE TITLE
  Is your final result after CRF

### ISSUE THREAD

**Issue by Andylijinpan** [chenqi1126/SIPE#6]
Because the result I reproduced (after irnet processing), the Miou of train is 68. X, and the result of cam is consistent with your 58.5

**Comment by chenqi1126** [comment]
Hi @Andylijinpan, 

The pseudo labels on train set do not use extra CRF after irn. Your result (68.X) looks like no problem.

**Comment by Andylijinpan** [comment]
> 

谢谢你的回答，大佬。
对于irnet后的训练集结果68.x，我担心我这个结果通过deeplabv2训练完可能达不到和你的结果一样高，我的这个结果真的可以吗？

**Comment by Andylijinpan** [comment]
@chenqi1126 
谢谢你的回答，大佬。
对于irnet后的训练集结果68.x，我担心我这个结果通过deeplabv2训练完可能达不到和你的结果一样高，我的这个结果真的可以吗？

**Comment by Andylijinpan** [comment]
@chenqi1126 另外，大佬方便给一下后半段v2训练的代码吗，我好直接用你的权重

**Comment by chenqi1126** [comment]
利用伪标签训练全监督模型的代码是直接使用现有项目，你可以在readme里面找到，只需要修改路径就可以运行。

**Comment by Andylijinpan** [comment]
> 利用伪标签训练全监督模型的代码是直接使用现有项目，你可以在readme里面找到，只需要修改路径就可以运行。
谢谢您的回答

**Comment by henry227** [comment]
Hello, I want to use the pseudo-label after irnet training to train the fully supervised model of v2, is it the path to replace the real dataset with pseudo-label
